### ISSUE TITLE
About 'uniprot.human.scratch_outputs.w_sps.tab_corrected' file

### ISSUE THREAD

**Issue by baehaeli** [Shen-Lab/DeepAffinity#10]
Hello, I am very interested in your work.

I find the 'uniprot.human.scratch_outputs.w_sps.tab_corrected' file 
in the path where '/data/dataset/uniprot.human.scratch_outputs.w_sps.tab_corrected/'.
It seems to have SPS mapping.
but It has different SPS with 'protein_sequence_SPS_mapping' file.

For example, in case of 'CP3A4', which sequence is 
'MALIPDLAMETWLLLAVSLVLLYLYGTHSHGLFKKLGIPGPTPLPFLGNILSYHKGFCMFDMECHKKYGKVWGFYDGQQPVLAITDPDMIKTVLVKECYSVFTNRRPFGPVGFMKSAISIAEDEEWKRLRSLLSPTFTSGKLKEMVPIIAQYGDVLVRNLRREAETGKPVTLKDVFGAYSMDVITSTSFGVNIDSLNNPQDPFVENTKKLLRFDFLDPFFLSITVFPFLIPILEVLNICVFPREVTNFLRKSVKRMKESRLEDTQKHRVDFLQLMIDSQNSKETESHKALSDLELVAQSIIFIFAGYETTSSVLSFIMYELATHPDVQQKLQEEIDAVLPNKAPPTYDTVLQMEYLDMVVNETLRLFPIAMRLERVCKKDVEINGMFIPKGVVVMIPSYALHRDPKYWTEPEKFLPERFSKKNKDNIDPYIYTPFGSGPRNCIGMRFALMNMKLALIRVLQNFSFKPCKETQIPLKLSLGGLLQPEKPVVLKVESRDGTVSGA'

In 'protein_sequence_SPS_mapping' file, The sps of this protein is
'ANGL,CEGL,AEKM,CEKS,BNDS,CNTS,BNGS,ANDM,CEKL,AEKL,CEDS,ANTL,CETM,AEDM,CEDS,ANGL,CEGS,AEKL,CEKS,AEDM,CEKM,ANDM,CNDS,ANDL,CETM,AEDM,CNKM,BEGM,CEKS,BNGS,ANTS,CEDM,AEKM,CETL,ANGL,CETL,BEDS,CEDM'

However, in  'uniprot.human.scratch_outputs.w_sps.tab_corrected' file, The sps of this protein is
'ANGL,CEKS,AEKS,CEGM,AEKL,BNGL,AEDM,CETM,AEKS,CEDS,AEDL,CEKS,ANTL,CETM,AEDS,CEDM,AEGL,CEGS,AEKL,CEDM,AETM,CEKM,ANDL,CEGM,ANDL,CNKM,BEGM,CEKS,ANGM,CEKL,ANGL,CETL,BEDS,CEDM'

I would like to know why they are different though they have same protein sequence.
Also Is it ok to use sps in 'uniprot.human.scratch_outputs.w_sps.tab_corrected' file for training and testing the DeepAffinity model.

Thank you,

**Comment by Shen-Lab** [comment]
Thank you for your interest in DeepAffinity.  'protein_sequence_SPS_mapping' Is prepared by ourself and used for the paper.  It is for proteins in bindingdb so besides other species it is a subset for human proteome.  ‘uniprot.human.scratch_outputs.w_sps.tab_corrected’ is kindly prepared by Dr. Tomas Babak at Queens University in 2021. It included all human proteome and was done after the publication.  
We didn’t compare the two files to see whether they are consistent in the intersection. So thank you for the note!  About your example, it appears that some secondary structure elements’ predicted overall secondary structure type or solvent exposure were not consistent, possibly due to different versions of SCRATCH for the corresponding prediction.  Their source  amino acid sequences in this case seem to be the same uniprot sequence though.

**Comment by baehaeli** [comment]
Thank you so much!
