### ISSUE TITLE
Pubchem fingerprints

### ISSUE THREAD

**Issue by vijec** [Shen-Lab/DeepAffinity#3]
Is it possible to share the code that was used to generate the pubchem fingerprints?

**Comment by AstroSign** [comment]
Hi,

Thanks for your question. You can refer to the script under the fold "DeepAffinity/data/script/split_data_script/pubchem/". The detail description is the 4th step in the "README" under "DeepAffinity/data/script/split_data_script".

Basically, you need to download data from  https://pubchem.ncbi.nlm.nih.gov/pc_fetch/pc_fetch.cgi based on the CIDs of your compound data. Then "> <PUBCHEM_CACTVS_SUBSKEYS>" term in the result file is firngerprint and you can extract it directly by our script "getCID_Feature.py". 

It's worth noting that our DeepAffinity model didn't use those fingerprint and they are for baseline method only. In addition, since the total number of families keeps increasing, the number of digits of fingerprint may change as well. You can change our script correspondingly if there's an error or report here so that I can help you with that.

Thanks.

**Comment by vijec** [comment]
Thanks!
